color0 #131316
color1 #ffb4ab
color2 #bfc2ff
color3 #c5c4dd
color4 #e8b9d5
color5 #bfc2ff
color6 #c5c4dd
color7 #e5e1e6
color8 #918f9a
color9 #ffb4ab
color10 #bfc2ff
color11 #c5c4dd
color12 #e8b9d5
color13 #bfc2ff
color14 #c5c4dd
color15 #e5e1e6

cursor                #e5e1e6
cursor_text_color     #131316
background            #131316
foreground            #e5e1e6
selection_foreground  #c7c5d0
selection_background  #46464f
active_border_color   #bfc2ff
inactive_border_color #46464f
url_color             #bfc2ff

active_tab_foreground   #202578
active_tab_background   #bfc2ff
inactive_tab_foreground #c7c5d0
inactive_tab_background #46464f
cursor_trail_color      #c7c5d0
