#!/usr/bin/env bash

RESET=$'\e[0m'
BOLD=$'\e[1m'
FG_RED=$'\e[0;31m'
FG_GREEN=$'\e[0;32m'
FG_YELLOW=$'\e[0;33m'
FG_BLUE=$'\e[0;34m'
FG_MAGENTA=$'\e[0;35m'
FG_WHITE=$'\e[0;37m'
FG_DARKGRAY=$'\e[0;90m'

LANGUAGE="en"
[[ "${LANG}" == "ru"* ]] && LANGUAGE="ru"

safe_read() {
    local prompt="$1"
    local var_name="$2"
    local input=""
    local char=""

    read -rsn10000 -t 0.01

    echo -n -e "$prompt"

    stty -echo
    while true; do
        read -rsn1 char

        if [[ "$char" == $'\x1b' ]]; then
            read -rsn10 -t 0.001 garbage
            continue
        fi

        if [[ "$char" == "" ]]; then
            echo ""
            break
        fi

        if [[ "$char" == $'\x7f' ]]; then
            if [ -n "$input" ]; then
                input="${input%?}"
                echo -ne "\b \b"
            fi
            continue
        fi

        echo -n "$char"
        input+="$char"
    done
    stty echo

    eval "$var_name=\"$input\""
}

press_enter_to_continue() {
    echo -e "\n${FG_YELLOW}${BOLD}${L_INFO_PRESS_ENTER}${RESET}"
    stty -echo
    while read -rsn1 -t 0.1 garbage; do :; done

    while true; do
        read -rsn1 key
        [[ "$key" == "" ]] && break
        if [[ "$key" == $'\x1b' ]]; then
            read -rsn10 -t 0.01 garbage
        fi
    done
    stty echo
}

if [ "$LANGUAGE" = "ru" ]; then
    L_ERROR_PREFIX="Ошибка:"
    L_SUCCESS_PREFIX="Успех!"
    L_INFO_CANCEL="Отмена."
    L_ERROR_INVALID_CHOICE="Неверный выбор!"
    L_INFO_PRESS_ENTER="Нажмите Enter для продолжения..."

    L_INSTALL_WELCOME="${FG_BLUE}${BOLD}--- Добро пожаловать в конфигуратор slowfetch! ---${RESET}"
    L_INSTALL_FIRST_RUN="Обнаружен первый запуск. Сейчас мы настроим окружение для Fastfetch."
    L_INSTALL_DEP_CHECK="${FG_YELLOW}Шаг 1/3: Проверка зависимостей...${RESET}"
    L_INSTALL_ALIAS_SETUP="${FG_YELLOW}Шаг 2/3: Настройка основного alias'а 'slowfetch'...${RESET}"
    L_INSTALL_PERFORMING="${FG_YELLOW}Шаг 3/3: Установка файлов в ${BOLD}${CONFIG_DIR}${RESET}...${RESET}"
    L_INSTALL_BACKING_UP="Существующая конфигурация в ${CONFIG_DIR} будет перемещена в бэкап."
    L_INSTALL_CONFIG_ALIAS="Создание alias'а для запуска конфигуратора..."
    L_INSTALL_COMPLETE_HEADER="${FG_GREEN}${BOLD}--- Установка завершена! ---${RESET}"
    L_INSTALL_COMPLETE_BODY="Все файлы были установлены. Вы можете безопасно удалить исходную папку, откуда вы запустили скрипт."
    L_INSTALL_COMPLETE_ALIAS_SLOWFETCH="Для запуска Fastfetch используйте команду '${BOLD}slowfetch${RESET}'."
    L_INSTALL_COMPLETE_ALIAS_CONFIG="Для повторного запуска этого конфигуратора используйте команду '${BOLD}slowfetch-config${RESET}'."
    L_INSTALL_RESTARTING="Перезапускаем конфигуратор из нового местоположения..."
    L_PROMPT_CONTINUE_OR_EXIT="\nНажмите Enter для продолжения установки или введите 'exit' для выхода: "
    L_PROMPT_RELOAD_SHELL="\n${BOLD}Запустить новую сессию оболочки, чтобы применить изменения сейчас? (y/N):${RESET} "
    L_INFO_RELOADING_SHELL="Запускаем новую сессию оболочки..."

    L_UNINSTALL_CONFIRM="Вы уверены, что хотите ${FG_RED}ПОЛНОСТЬЮ удалить${RESET} slowfetch? (y/N) "
    L_UNINSTALL_WARNING="Это действие удалит алиасы и все конфигурационные файлы из ${CONFIG_DIR}."
    L_UNINSTALL_STARTED="${FG_YELLOW}Начинаем удаление...${RESET}"
    L_UNINSTALL_ALIASES="Удаление алиасов из конфигов оболочки..."
    L_UNINSTALL_FILES="Удаление файлов проекта Fastfetch..."
    L_UNINSTALL_RESTORE="Восстановление из бэкапа..."
    L_UNINSTALL_NO_BACKUP="Бэкап не найден, просто удаляем."
    L_UNINSTALL_COMPLETE="${FG_GREEN}Удаление завершено.${RESET} Восстановлен предыдущий конфиг (если он был)."
    L_UNINSTALL_GOODBYE="Прощайте!"
    L_INFO_CACHE_CLEARED="${FG_GREEN}Кэш github_stars очищен.${RESET}"
    L_INFO_SAVING="Сохранение изменений..."
    L_INFO_BACKUP_SAVED_TO="Ваша предыдущая конфигурация сохранена в: ${BOLD}${user_backup_file}${RESET}"
    L_INFO_DEPENDENCIES_WARNING_HEADER="${FG_RED}${BOLD}Внимание:${RESET}${FG_RED} Не найдены следующие зависимости для используемых скриптов Fastfetch:${RESET}"
    L_INFO_DEPENDENCIES_WARNING_FOOTER="Некоторые модули могут не работать или вызывать ошибки при запуске Fastfetch."
    L_INFO_EXITING="Выход."
    L_INFO_EXITING_NO_SAVE="Выход без сохранения."
    L_INFO_MODULES_HEADER="--- Текущие модули в конфигурации ---"
    L_INFO_SEPARATOR="--- разделитель ---"
    L_INFO_MOVING_MODULE="Перемещаем модуль: ${BOLD}${module_name}${RESET}"
    L_INFO_MODULE_ALREADY_TOP="Модуль уже наверху!"
    L_INFO_MODULE_ALREADY_BOTTOM="Модуль уже внизу!"
    L_PROMPT_MOVE_MODULE_NUM="Введите номер модуля для перемещения: "
    L_PROMPT_MOVE_MODULE_DIR="Переместить вверх (u) или вниз (d)? "
    L_SUCCESS_MODULE_MOVED="Модуль успешно перемещен!"
    L_PROMPT_REMOVE_MODULE_NUM="Введите номер модуля для удаления: "
    L_PROMPT_REMOVE_MODULE_CONFIRM="Вы уверены, что хотите удалить этот модуль? (y/N) "
    L_SUCCESS_MODULE_REMOVED="Модуль успешно удален!"
    L_PROMPT_ADD_MODULE_KEY="Введите ключ для модуля (или Enter для пропуска): "
    L_PROMPT_ADD_MODULE_POS="Введите позицию для вставки (или Enter для добавления в конец): "
    L_SUCCESS_MODULE_ADDED="Модуль успешно добавлен!"
    L_INFO_ADD_MODULE_HEADER="--- Добавление кастомного модуля ---"
    L_INFO_NO_FREE_SCRIPTS="Свободных скриптов для добавления не найдено."
    L_INFO_ADD_MODULE_SELECT_SCRIPT="Выберите скрипт для добавления:"
    L_INFO_ADD_MODULE_CANCEL_OPTION="--[ Отмена ]--"
    L_INFO_ADD_MODULE_INVALID_CHOICE="Неверный выбор. Попробуйте еще раз."
    L_INFO_ADD_MODULE_CANCELED="Добавление отменено."
    L_INFO_ADD_MODULE_CHOOSE_POS="--- Выберите место для нового модуля ---"
    L_INFO_CONFIGURE_MODULES_HEADER="--- Настройка модулей ---"
    L_PROMPT_CONFIGURE_MODULE="Выберите модуль для настройки [1-3]: "
    L_INFO_CONFIGURE_GH_STARS="Настроить модуль ${BOLD}Github Stars${RESET}"
    L_INFO_CONFIGURE_NEWS_SOURCE="Настроить ${BOLD}Источник новостей${RESET}"
    L_INFO_CONFIGURE_CURRENCY_RATE="Настроить ${BOLD}Валютные курсы${RESET}"
    L_INFO_FETCHING_REPOS="Получение списка репозиториев..."
    L_INFO_GH_NO_REPOS="Не удалось найти репозитории для '$username'."
    L_INFO_GH_SELECT_REPOS="Выберите репозитории (${BOLD}пробел${RESET} - выбрать, ${BOLD}enter${RESET} - подтвердить)."
    L_INFO_DIALOG_NOT_FOUND="(Утилита 'dialog' не найдена, используется упрощенный выбор)"
    L_INFO_GH_NO_REPOS_SELECTED="Не выбрано ни одного репозитория. Отмена."
    L_INFO_GH_CLEAR_CACHE_HINT="Для немедленного обновления очистите кэш: ${BOLD}rm ~/.cache/fastfetch/github_stars.cache${RESET}"
    L_PROMPT_GH_LOGIN_NOW="Войти в GitHub сейчас? (y/N): "
    L_ERROR_GH_LOGIN_FAILED="Не удалось войти в GitHub."
    L_PROMPT_GH_USERNAME="Введите имя пользователя GitHub: "
    L_PROMPT_GH_TRACK_REPO="Отслеживать репозиторий '$repo'? (y/N): "
    L_ERROR_SCRIPT_NOT_FOUND="Скрипт не найден."
    L_ERROR_GH_CLI_REQUIRED="Требуется GitHub CLI (gh). Установите его для настройки модуля."
    L_SUCCESS_GH_STARS_CONFIGURED="Модуль GitHub Stars настроен!"
    L_INFO_CONFIGURE_NEWS_HEADER="--- Настройка источника новостей ---"
    L_INFO_NEWS_SELECT_SOURCE="Выберите новый источник новостей:"
    L_PROMPT_NEWS_SOURCE="Выберите источник [1-4]: "
    L_INFO_NEWS_SOURCE_1="OpenNet.ru (RU)"
    L_INFO_NEWS_SOURCE_2="Phoronix (EN)"
    L_INFO_NEWS_SOURCE_3="LWN.net (EN)"
    L_INFO_NEWS_SOURCE_4="Отмена"
    L_SUCCESS_NEWS_SOURCE_SAVED="Источник новостей сохранен!"
    L_INFO_NEWS_CHANGES_APPLIED="Изменения применятся при следующем запуске fastfetch."
    L_INFO_CONFIGURE_CURRENCY_HEADER="--- Настройка модуля валютных курсов ---"
    L_INFO_CURRENCY_SELECT_SOURCE="Выберите источник валютных курсов:"
    L_INFO_CURRENCY_SOURCE_1="Центральный Банк России (CBR)"
    L_INFO_CURRENCY_SOURCE_2="Европейский Центральный Банк (ECB)"
    L_INFO_CURRENCY_PROMPT_CBR="Введите код валюты (например, USD, EUR, CNY): "
    L_INFO_CURRENCY_PROMPT_ECB_FROM="Введите исходную валюту (например, USD): "
    L_INFO_CURRENCY_PROMPT_ECB_TO="Введите целевую валюту (например, EUR): "
    L_SUCCESS_CURRENCY_CONFIGURED="Настройки валютных курсов сохранены!"
    L_PROMPT_RESET_CONFIRM="Вы уверены, что хотите сбросить конфигурацию к начальной? (y/N) "
    L_SUCCESS_CONFIG_RESET="Конфигурация сброшена к начальной!"
    L_ERROR_CONFIG_NOT_FOUND="Файл конфигурации не найден."
    L_ERROR_DEFAULT_CONFIG_NOT_FOUND="Файл конфигурации по умолчанию не найден."
    L_SUCCESS_CONFIG_SAVED="Конфигурация сохранена!"
    L_ERROR_JQ_NOT_FOUND="Утилита 'jq' не найдена."
    L_ERROR_JQ_INSTALL_HINT="Установите 'jq' для работы с JSON файлами."
    L_INFO_CREATING_ALIAS_HEADER="--- Создание Alias '${alias_name}' ---"
    L_INFO_ALIAS_CONFIG_CREATED="Создаем файл конфигурации: $config_file"
    L_INFO_ALIAS_APPLY_HINT="\nЧтобы изменения вступили в силу, выполните:"
    L_INFO_ALIAS_RESTART_HINT="Или просто перезапустите ваш терминал."
    L_SUCCESS_ALIAS_CREATED="Alias успешно создан!"
    L_ERROR_SHELL_NOT_SUPPORTED="Ваша оболочка не поддерживается. Поддерживаются только bash и zsh."
    L_ERROR_INVALID_INPUT="Неверный ввод!"
    L_ERROR_INVALID_MODULE_NUM="Неверный номер модуля!"
    L_ERROR_INVALID_DIRECTION="Неверное направление!"

    L_INFO_CONFIGURE_GH_STARS_HEADER="--- Настройка GitHub Stars ---"
    L_INFO_CONFIGURE_GH_FROM_REPOS="Выбрать из моих репозиториев (нужен gh)"
    L_INFO_CONFIGURE_GH_MANUAL="Ввести вручную (owner/repo)"
    L_INFO_BACK="Назад"
    L_PROMPT_CHOICE="Выбор"
    L_PROMPT_GH_SELECT_REPOS="Выберите репозитории (Пробел - выбор, Enter - подтвердить):"
    L_PROMPT_GH_MANUAL_INPUT="Введите ID репозиториев через пробел"
    L_HINT_GH_MANUAL_EXAMPLE="Пример: cli/cli google/googletest"
    L_PROMPT_GH_ID="ID:"
    L_ERROR_GH_REPOS_EMPTY="Ошибка: Список пуст. Проверьте 'gh auth status'."
    L_ERROR_GH_SKIP_ITEM="Пропуск '$item' (неверный формат)"
    L_TUI_GH_REPOS_TITLE="${BOLD}${FG_MAGENTA}   ВЫБОР РЕПОЗИТОРИЕВ GITHUB${RESET}"
    L_TUI_GH_REPOS_HINT="${FG_WHITE}Пробел: Выбор | Enter: Подтвердить | q/Esc: Отмена${RESET}"

    L_TUI_ADD_MODULE_TITLE="${BOLD}${FG_GREEN}  ✚ ДОБАВЛЕНИЕ МОДУЛЯ${RESET}"
    L_TUI_EDIT_MODULE_TITLE="${BOLD}${FG_BLUE}  ⚙ РЕДАКТОР МОДУЛЕЙ${RESET}"
    L_TUI_NAVIGATION_HINT="    ${FG_WHITE}Стрелки: Навигация | Enter: Выбрать | Esc/q: Отмена${RESET}"
    L_TUI_MOVING_HINT="    ${FG_WHITE}Стрелки: Двигать | Enter: Отпустить | Esc: Отмена${RESET}"
    L_TUI_NAVIGATION_STATUS="${FG_BLUE}${BOLD}  ○ НАВИГАЦИЯ (Всего: %s)${RESET}"
    L_TUI_ACTION_HINT="    ${FG_WHITE}Enter: Схватить | d: Удалить | a: Добавить | s: Сохранить | q: Выход${RESET}"
    L_TUI_EMPTY_LIST="${FG_RED}    Список пуст. Нажмите 'a' для добавления модуля.${RESET}"
    L_TUI_MOVING_STATUS="${FG_YELLOW}${BOLD}  ● ПЕРЕМЕЩЕНИЕ: %s${RESET}"

    L_SUBMENU_CONFIGURE_TITLE="${BOLD}${L_INFO_CONFIGURE_MODULES_HEADER}${RESET}"
    L_SUBMENU_CONFIGURE_OPTION_1="GitHub Stars"
    L_SUBMENU_CONFIGURE_OPTION_2="Источник новостей"
    L_SUBMENU_CONFIGURE_OPTION_3="Курсы валют"
    L_SUBMENU_CONFIGURE_BACK="Назад"
    L_PROMPT_SUBMENU_CHOICE="Выбор: "

    L_MAIN_MENU_TITLE="${BOLD}--- Конфигуратор Fastfetch ---${RESET}"
    L_MAIN_MENU_1="Управление модулями (Порядок / Удаление / Добавление)"
    L_MAIN_MENU_2="Настройка параметров модулей"
    L_MAIN_MENU_R="Сбросить конфигурацию к начальной"
    L_MAIN_MENU_A="Перенастроить alias 'slowfetch'"
    L_MAIN_MENU_U="${FG_RED}u. Удалить slowfetch${RESET}"
    L_MAIN_MENU_S="${FG_GREEN}s. Сохранить изменения и выйти${RESET}"
    L_MAIN_MENU_Q="${FG_RED}q. Выйти БЕЗ сохранения${RESET}"
    L_PROMPT_CHOOSE_ACTION="Выберите действие: "
else
    L_ERROR_PREFIX="Error:"
    L_SUCCESS_PREFIX="Success!"
    L_INFO_CANCEL="Canceled."
    L_ERROR_INVALID_CHOICE="Invalid choice!"
    L_INFO_PRESS_ENTER="Press Enter to continue..."

    L_INSTALL_WELCOME="${FG_BLUE}${BOLD}--- Welcome to the slowfetch configurator! ---${RESET}"
    L_INSTALL_FIRST_RUN="First run detected. We will now set up the environment for Fastfetch."
    L_INSTALL_DEP_CHECK="${FG_YELLOW}Step 1/3: Checking dependencies...${RESET}"
    L_INSTALL_ALIAS_SETUP="${FG_YELLOW}Step 2/3: Setting up the main 'slowfetch' alias...${RESET}"
    L_INSTALL_PERFORMING="${FG_YELLOW}Step 3/3: Installing files to ${BOLD}${CONFIG_DIR}${RESET}...${RESET}"
    L_INSTALL_BACKING_UP="Existing configuration in ${CONFIG_DIR} will be backed up."
    L_INSTALL_CONFIG_ALIAS="Creating an alias for the configurator..."
    L_INSTALL_COMPLETE_HEADER="${FG_GREEN}${BOLD}--- Installation Complete! ---${RESET}"
    L_INSTALL_COMPLETE_BODY="All files have been installed. You can now safely delete the original folder you ran this script from."
    L_INSTALL_COMPLETE_ALIAS_SLOWFETCH="Use the '${BOLD}slowfetch${RESET}' command to run Fastfetch."
    L_INSTALL_COMPLETE_ALIAS_CONFIG="Use the '${BOLD}slowfetch-config${RESET}' command to run this configurator again."
    L_INSTALL_RESTARTING="Restarting the configurator from the new location..."
    L_PROMPT_CONTINUE_OR_EXIT="\nPress Enter to continue with the installation, or type 'exit' to quit: "
    L_PROMPT_RELOAD_SHELL="\n${BOLD}Start a new shell session to apply the changes now? (y/N):${RESET} "
    L_INFO_RELOADING_SHELL="Starting new shell session..."

    L_UNINSTALL_CONFIRM="Are you sure you want to ${FG_RED}COMPLETELY uninstall${RESET} slowfetch? (y/N) "
    L_UNINSTALL_WARNING="This will remove aliases and all configuration files from ${CONFIG_DIR}."
    L_UNINSTALL_STARTED="${FG_YELLOW}Starting uninstallation...${RESET}"
    L_UNINSTALL_ALIASES="Removing aliases from shell configs..."
    L_UNINSTALL_FILES="Removing Fastfetch project files..."
    L_UNINSTALL_RESTORE="Restoring from backup..."
    L_UNINSTALL_NO_BACKUP="No backup found, proceeding with deletion."
    L_UNINSTALL_COMPLETE="${FG_GREEN}Uninstallation complete.${RESET} Your previous config (if any) has been restored."
    L_UNINSTALL_GOODBYE="Goodbye!"
    L_INFO_CACHE_CLEARED="${FG_GREEN}GitHub Stars cache cleared.${RESET}"

    L_INFO_SAVING="Saving changes..."
    L_INFO_BACKUP_SAVED_TO="Your previous configuration has been saved to: ${BOLD}${user_backup_file}${RESET}"
    L_INFO_DEPENDENCIES_WARNING_HEADER="${FG_RED}${BOLD}Warning:${RESET}${FG_RED} The following dependencies for the used Fastfetch scripts were not found:${RESET}"
    L_INFO_DEPENDENCIES_WARNING_FOOTER="Some modules may not work or may cause errors when running Fastfetch."
    L_INFO_EXITING="Exiting."
    L_INFO_EXITING_NO_SAVE="Exiting without saving."
    L_INFO_MODULES_HEADER="--- Current modules in configuration ---"
    L_INFO_SEPARATOR="--- separator ---"
    L_INFO_MOVING_MODULE="Moving module: ${BOLD}${module_name}${RESET}"
    L_INFO_MODULE_ALREADY_TOP="Module is already at the top!"
    L_INFO_MODULE_ALREADY_BOTTOM="Module is already at the bottom!"
    L_PROMPT_MOVE_MODULE_NUM="Enter module number to move: "
    L_PROMPT_MOVE_MODULE_DIR="Move up (u) or down (d)? "
    L_SUCCESS_MODULE_MOVED="Module moved successfully!"
    L_PROMPT_REMOVE_MODULE_NUM="Enter module number to remove: "
    L_PROMPT_REMOVE_MODULE_CONFIRM="Are you sure you want to remove this module? (y/N) "
    L_SUCCESS_MODULE_REMOVED="Module removed successfully!"
    L_PROMPT_ADD_MODULE_KEY="Enter key for module (or Enter to skip): "
    L_PROMPT_ADD_MODULE_POS="Enter position for insertion (or Enter to add at the end): "
    L_SUCCESS_MODULE_ADDED="Module added successfully!"
    L_INFO_ADD_MODULE_HEADER="--- Add Custom Module ---"
    L_INFO_NO_FREE_SCRIPTS="No available scripts to add were found."
    L_INFO_ADD_MODULE_SELECT_SCRIPT="Select a script to add:"
    L_INFO_ADD_MODULE_CANCEL_OPTION="--[ Cancel ]--"
    L_INFO_ADD_MODULE_INVALID_CHOICE="Invalid choice. Please try again."
    L_INFO_ADD_MODULE_CANCELED="Addition canceled."
    L_INFO_ADD_MODULE_CHOOSE_POS="--- Choose a position for the new module ---"
    L_INFO_CONFIGURE_MODULES_HEADER="--- Configure Modules ---"
    L_PROMPT_CONFIGURE_MODULE="Select module to configure [1-3]: "
    L_INFO_CONFIGURE_GH_STARS="Configure ${BOLD}Github Stars${RESET} module"
    L_INFO_CONFIGURE_NEWS_SOURCE="Configure ${BOLD}News Source${RESET}"
    L_INFO_CONFIGURE_CURRENCY_RATE="Configure ${BOLD}Currency Rates${RESET}"
    L_INFO_FETCHING_REPOS="Fetching repository list..."
    L_INFO_GH_NO_REPOS="Could not find repositories for '$username'."
    L_INFO_GH_SELECT_REPOS="Select repositories (${BOLD}space${RESET} - select, ${BOLD}enter${RESET} - confirm)."
    L_INFO_DIALOG_NOT_FOUND="('dialog' utility not found, using simplified selection)"
    L_INFO_GH_NO_REPOS_SELECTED="No repositories selected. Aborting."
    L_INFO_GH_CLEAR_CACHE_HINT="To apply changes immediately, clear the cache: ${BOLD}rm ~/.cache/fastfetch/github_stars.cache${RESET}"
    L_PROMPT_GH_LOGIN_NOW="Login to GitHub now? (y/N): "
    L_ERROR_GH_LOGIN_FAILED="Failed to login to GitHub."
    L_PROMPT_GH_USERNAME="Enter GitHub username: "
    L_PROMPT_GH_TRACK_REPO="Track repository '$repo'? (y/N): "
    L_ERROR_SCRIPT_NOT_FOUND="Script not found."
    L_ERROR_GH_CLI_REQUIRED="GitHub CLI (gh) required. Install it to configure the module."
    L_SUCCESS_GH_STARS_CONFIGURED="GitHub Stars module configured!"
    L_INFO_CONFIGURE_NEWS_HEADER="--- Configure News Source ---"
    L_INFO_NEWS_SELECT_SOURCE="Select a new news source:"
    L_PROMPT_NEWS_SOURCE="Select source [1-4]: "
    L_INFO_NEWS_SOURCE_1="OpenNet.ru (RU)"
    L_INFO_NEWS_SOURCE_2="Phoronix (EN)"
    L_INFO_NEWS_SOURCE_3="LWN.net (EN)"
    L_INFO_NEWS_SOURCE_4="Cancel"
    L_SUCCESS_NEWS_SOURCE_SAVED="News source saved!"
    L_INFO_NEWS_CHANGES_APPLIED="Changes will be applied on the next fastfetch run."
    L_INFO_CONFIGURE_CURRENCY_HEADER="--- Configure Currency Rate Module ---"
    L_INFO_CURRENCY_SELECT_SOURCE="Select a currency rate source:"
    L_INFO_CURRENCY_SOURCE_1="Central Bank of Russia (CBR)"
    L_INFO_CURRENCY_SOURCE_2="European Central Bank (ECB)"
    L_INFO_CURRENCY_PROMPT_CBR="Enter currency code (e.g., USD, EUR, CNY): "
    L_INFO_CURRENCY_PROMPT_ECB_FROM="Enter source currency (e.g., USD): "
    L_INFO_CURRENCY_PROMPT_ECB_TO="Enter target currency (e.g., EUR): "
    L_SUCCESS_CURRENCY_CONFIGURED="Currency rate settings saved!"
    L_PROMPT_RESET_CONFIRM="Are you sure you want to reset the configuration to default? (y/N) "
    L_SUCCESS_CONFIG_RESET="Configuration reset to default!"
    L_ERROR_CONFIG_NOT_FOUND="Configuration file not found."
    L_ERROR_DEFAULT_CONFIG_NOT_FOUND="Default configuration file not found."
    L_SUCCESS_CONFIG_SAVED="Configuration saved!"
    L_ERROR_JQ_NOT_FOUND="'jq' utility not found."
    L_ERROR_JQ_INSTALL_HINT="Install 'jq' to work with JSON files."
    L_INFO_CREATING_ALIAS_HEADER="--- Create Alias '${alias_name}' ---"
    L_INFO_ALIAS_CONFIG_CREATED="Creating config file: $config_file"
    L_INFO_ALIAS_APPLY_HINT="\nTo apply the changes, run:"
    L_INFO_ALIAS_RESTART_HINT="Or simply restart your terminal."
    L_SUCCESS_ALIAS_CREATED="Alias created successfully!"
    L_ERROR_SHELL_NOT_SUPPORTED="Your shell is not supported. Only bash and zsh are supported."
    L_ERROR_INVALID_INPUT="Invalid input!"
    L_ERROR_INVALID_MODULE_NUM="Invalid module number!"
    L_ERROR_INVALID_DIRECTION="Invalid direction!"

    L_INFO_CONFIGURE_GH_STARS_HEADER="--- Configure GitHub Stars ---"
    L_INFO_CONFIGURE_GH_FROM_REPOS="Select from my repositories (gh required)"
    L_INFO_CONFIGURE_GH_MANUAL="Enter manually (owner/repo)"
    L_INFO_BACK="Back"
    L_PROMPT_CHOICE="Choice"
    L_PROMPT_GH_SELECT_REPOS="Select repositories (Space - select, Enter - confirm):"
    L_PROMPT_GH_MANUAL_INPUT="Enter repository IDs separated by space"
    L_HINT_GH_MANUAL_EXAMPLE="Example: cli/cli google/googletest"
    L_PROMPT_GH_ID="ID:"
    L_ERROR_GH_REPOS_EMPTY="Error: List is empty. Check 'gh auth status'."
    L_ERROR_GH_SKIP_ITEM="Skipping '$item' (invalid format)"
    L_TUI_GH_REPOS_TITLE="${BOLD}${FG_MAGENTA}   GITHUB REPOS SELECTION${RESET}"
    L_TUI_GH_REPOS_HINT="${FG_WHITE}Space: Toggle | Enter: Confirm | q/Esc: Cancel${RESET}"

    L_TUI_ADD_MODULE_TITLE="${BOLD}${FG_GREEN}  ✚ ADD MODULE${RESET}"
    L_TUI_EDIT_MODULE_TITLE="${BOLD}${FG_BLUE}  ⚙ MODULE EDITOR${RESET}"
    L_TUI_NAVIGATION_HINT="    ${FG_WHITE}Arrows: Navigation | Enter: Select | Esc/q: Cancel${RESET}"
    L_TUI_MOVING_HINT="    ${FG_WHITE}Arrows: Move | Enter: Release | Esc: Cancel${RESET}"
    L_TUI_NAVIGATION_STATUS="${FG_BLUE}${BOLD}  ○ NAVIGATION (Total: %s)${RESET}"
    L_TUI_ACTION_HINT="    ${FG_WHITE}Enter: Grab | d: Delete | a: Add | s: Save | q: Exit${RESET}"
    L_TUI_EMPTY_LIST="${FG_RED}    List is empty. Press 'a' to add a module.${RESET}"
    L_TUI_MOVING_STATUS="${FG_YELLOW}${BOLD}  ● MOVING: %s${RESET}"

    L_SUBMENU_CONFIGURE_TITLE="${BOLD}${L_INFO_CONFIGURE_MODULES_HEADER}${RESET}"
    L_SUBMENU_CONFIGURE_OPTION_1="GitHub Stars"
    L_SUBMENU_CONFIGURE_OPTION_2="News Source"
    L_SUBMENU_CONFIGURE_OPTION_3="Currency Rates"
    L_SUBMENU_CONFIGURE_BACK="Back"
    L_PROMPT_SUBMENU_CHOICE="Choice: "

    L_MAIN_MENU_TITLE="${BOLD}--- Fastfetch Configurator ---${RESET}"
    L_MAIN_MENU_1="Manage Modules (Reorder / Delete / Add)"
    L_MAIN_MENU_2="Configure Module Settings"
    L_MAIN_MENU_R="Reset configuration to default"
    L_MAIN_MENU_A="Re-configure 'slowfetch' alias"
    L_MAIN_MENU_U="${FG_RED}u. Uninstall slowfetch${RESET}"
    L_MAIN_MENU_S="${FG_GREEN}s. Save changes and exit${RESET}"
    L_MAIN_MENU_Q="${FG_RED}q. Quit WITHOUT saving${RESET}"
    L_PROMPT_CHOOSE_ACTION="Choose an action: "
fi
