
-- Generated by hyprconf2lua v1.8.1
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.monitor({
    output   = "",
    mode     = "preferred",
    position = "auto",
    scale    = 1,
})

--exec-once = /usr/bin/quickshell -c noctalia-shell




hl.env("XCURSOR_SIZE", 24)

hl.config({
    input = {
        kb_layout = "us,ru",
        kb_options = "grp:alt_shift_toggle",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false,
        },
        numlock_by_default = false,
        sensitivity = 0,
        -- -1.0 - 1.0, 0 means no modification.
    },
})

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,
        border_size = 2,
        layout = "dwindle",
        col = {
            active_border = "0xff3a71b3",
            inactive_border = "0x663a71b3",
        },
    },
})

hl.config({
    decoration = {
        rounding = 15,
        -- Размытие
        blur = {
            enabled = true,
            size = 5,
            passes = 2,
            ignore_opacity = true,
            new_optimizations = true,
        },
        active_opacity = 1.0,
        inactive_opacity = 0.9,
        fullscreen_opacity = 1.0,
    },
})

hl.config({
    animations = {
        enabled = true,
    },
})
hl.animation({ leaf = "windowsIn", enabled = true, speed = 6, bezier = "default", style = "slide" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 6, bezier = "default", style = "slide" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 7, bezier = "default", style = "slide" })

hl.config({
    dwindle = {
        preserve_split = true,
        -- you probably want this
    },
})

local mainMod = "SUPER"

hl.bind("SUPER + tab", hl.dsp.exec_cmd("killall -SIGUSR1 waybar"))

hl.bind(mainMod .. " + " .. "Escape", hl.dsp.exec_cmd("rofi -show power-menu -modi power-menu:rofi-power-menu"))

hl.bind("SUPER + R", hl.dsp.exec_cmd("wofi --show drun"))

hl.bind(mainMod .. " + " .. "S", hl.dsp.exec_cmd("steam"))

hl.bind(mainMod .. " + " .. "C", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "F", hl.dsp.window.float())

hl.bind("SUPER + E", hl.dsp.layout("swapsplit"))

hl.bind(mainMod .. " + " .. "T", hl.dsp.layout("togglesplit"))

hl.bind("Print", hl.dsp.exec_cmd("bash -c 'grim -g \"$(slurp)\" - | wl-copy'"))

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 0, hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"))

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"))

hl.bind("ALT + D", hl.dsp.exec_cmd("rofi -show drun -show-icons"))

hl.bind("ALT + Tab", hl.dsp.focus({ workspace = "previous" }))

hl.bind("ALT + I", hl.dsp.exec_cmd("hyprlock"))

hl.bind("ALT + B", hl.dsp.exec_cmd("firefox"))

hl.bind("ALT + T", hl.dsp.exec_cmd("Telegram"))

hl.bind("ALT + X", hl.dsp.exec_cmd("kitty"))

hl.bind("ALT + y", hl.dsp.exec_cmd("/opt/yandex-music/yandexmusic"))

hl.bind("ALT + H", hl.dsp.exec_cmd("kitty lavat"))

hl.bind("ALT + J", hl.dsp.exec_cmd("kitty tty-clock -s -c -C 4 -t"))

hl.bind("ALT + F", hl.dsp.exec_cmd("kitty --hold fastfetch"))

hl.bind("ALT + G", hl.dsp.exec_cmd("kitty cava"))

hl.bind("ALT + R", hl.dsp.exec_cmd("kitty btop"))

hl.bind("ALT + C", hl.dsp.window.close())

hl.bind("ALT + Q", hl.dsp.exit())

hl.bind("ALT + A", hl.dsp.layout("swapsplit"))

hl.bind("ALT + S", hl.dsp.layout("togglesplit"))

hl.bind("ALT + E", hl.dsp.exec_cmd("dolphin"))

hl.bind("ALT + V", hl.dsp.window.float())

hl.bind("ALT + left", hl.dsp.focus({ direction = "left" }))

hl.bind("ALT + right", hl.dsp.focus({ direction = "right" }))

hl.bind("ALT + up", hl.dsp.focus({ direction = "up" }))

hl.bind("ALT + down", hl.dsp.focus({ direction = "down" }))

hl.bind("ALT + 1", hl.dsp.focus({ workspace = 1 }))

hl.bind("ALT + 2", hl.dsp.focus({ workspace = 2 }))

hl.bind("ALT + 3", hl.dsp.focus({ workspace = 3 }))

hl.bind("ALT + 4", hl.dsp.focus({ workspace = 4 }))

hl.bind("ALT + 5", hl.dsp.focus({ workspace = 5 }))

hl.bind("ALT + 6", hl.dsp.focus({ workspace = 6 }))

hl.bind("ALT + 7", hl.dsp.focus({ workspace = 7 }))

hl.bind("ALT + 8", hl.dsp.focus({ workspace = 8 }))

hl.bind("ALT + 9", hl.dsp.focus({ workspace = 9 }))

hl.bind("ALT + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind("ALT + SHIFT + 1", hl.dsp.window.move({ workspace = 1 , follow = false}))

hl.bind("ALT + SHIFT + 2", hl.dsp.window.move({ workspace = 2 , follow = false}))

hl.bind("ALT + SHIFT + 3", hl.dsp.window.move({ workspace = 3 , follow = false}))

hl.bind("ALT + SHIFT + 4", hl.dsp.window.move({ workspace = 4 , follow = false}))

hl.bind("ALT + SHIFT + 5", hl.dsp.window.move({ workspace = 5 , follow = false}))

hl.bind("ALT + SHIFT + 6", hl.dsp.window.move({ workspace = 6 , follow = false}))

hl.bind("ALT + SHIFT + 7", hl.dsp.window.move({ workspace = 7 , follow = false}))

hl.bind("ALT + SHIFT + 8", hl.dsp.window.move({ workspace = 8 , follow = false}))

hl.bind("ALT + SHIFT + 9", hl.dsp.window.move({ workspace = 9 , follow = false}))

hl.bind("ALT + SHIFT + 0", hl.dsp.window.move({ workspace = 10 , follow = false}))

hl.bind("ALT + mouse:272", hl.dsp.window.drag(), { mouse = true })

hl.bind("ALT + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { repeating = true, locked = true })

hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { repeating = true, locked = true })

hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { repeating = true, locked = true })

hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { repeating = true, locked = true })

hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { repeating = true, locked = true })

hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { repeating = true, locked = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })

hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })

hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("telegram-desktop -startintray")
    hl.exec_cmd("awww-daemon")
end)
